ip: "0.0.0.0"
http_port: 8080
grpc_port: 50051
internal_grpc_port: 50052

client_config:
  ip: swir-java-client
  http_port: 8090
  grpc_port: 50053

#client_executable: "client.jar"
pubsub:
  kafka:
    - brokers: [kafka:9094]
      consumer_topics:
        - consumer_topic: Response
          consumer_group: swir
          client_topic: SubscribeToAppA
        - consumer_topic: Response2
          consumer_group: swir
          client_topic: SubscribeToAppC
      producer_topics:
        - producer_topic: Request
          client_topic: ProduceToAppA
        - producer_topic: Request2
          client_topic: ProduceToAppC
      

  nats:
    - brokers:
        - nats://nats:4222
      consumer_topics:
        - consumer_topic: "Response"
          consumer_group: "swir"
          client_topic: "SubscribeToAppB"
        - consumer_topic: "Response2"
          consumer_group: "swir"
          client_topic: "SubscribeToAppD"
      producer_topics:
        - producer_topic: "Request"
          client_topic: "ProduceToAppB"
        - producer_topic: "Request2"
          client_topic: "ProduceToAppD"
          
  aws_kinesis: []
  
stores:  
  redis: []
  dynamodb: []


