version: '3.7'
# Sidecars layer. All sidecars are already deployed.
services:
  swir-example-si-configurator:
    networks:
      - swir-si
    image: swir-example-si-configurator:v0.3.1
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs
        
  swir-example-logger:
    networks:
      - swir-si
    image: jaegertracing/all-in-one:1.18
    depends_on:
      - swir-example-si-configurator
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
      - "16686:16686"
      - "14268"
      - "4250"
              

# step 1 
# Java gRCP
  orchestator_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.1
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs                


# step 2     
# python REST 
  books_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.1
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_books_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs        


# python REST 
  magazinges_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.1
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_magazine_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs        

        
volumes:
  swir_config:
  certs:
networks:
  swir-si:

