apiVersion: apps/v1
kind: Deployment
metadata:
  name: magazines
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: swir
    swir: magazines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-si-python-http-server:v0.3.1
        env:
          - name: port
            value: "8090"
