apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk
  annotations:
    "sidecar.jaegertracing.io/inject": "true"  
  labels:
    app: swir
    swir: helpdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-si-python-grpc-client:v0.3.1
        env:
          - name: sidecar
            value: "127.0.0.1:50051"
          - name: service_names
            value: "books,magazines"

