version: '3.7'
services:
  zookeeper:
    networks:
      - swir-net
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    networks:
      - swir-net
    image: wurstmeister/kafka
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nats:
    networks:
      - swir-net
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
      
  redis:
    networks:
      - swir-net
    image: redis
    ports:
      - "6379:6379"      

networks:
  swir-net:
